### ISSUE TITLE
Create multiple pages!? A little help please #3

### ISSUE THREAD

**Issue by BogdanXcode** [BogdanXcode/Home-Garden-Design#3]
I've written the code like this... but when I go in my browser on my page and i click on the link apper like this "Cannot GET /garden/inspiration"

extends ../../_component/layout/template

block cool-config
  -
    var myTitle ='Welcome to our page';
    var myDescription ='This is a WebPage for everyone who wants to build an awesome Garden';
    var landingPage = 'Home';
    var activeLink = '/Home/Garden Inspiration';

block primary-content
  h1 = Example
  p = description
  h2 Example

  p(title="this is a tooltip") This paragraph has a tooltip.

**Comment by marianzburlea** [comment]
well, "/garden/inspiration" is not the same as "/Home/Garden Inspiration"

**Comment by BogdanXcode** [comment]
i change it but is the same result "Cannot GET /garden/inspiration"
